# -*- coding: utf-8 -*-
"""python-pandas.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_lo3L3o8c8Z40HNEbiRUzzA0YK-VCcQ6

#Estudando pandas

* Anaconda é a principal distribuição para cientistas de dados que usam Python
* Jupyter é a nossa ferramenta para executar código Python e visualizar os dados
* Ambientes virtuais ajudam a isolar um projeto para definir a versão das bibliotecas e do próprio Python

# Relatório de análise I

## Importando a base de dados
"""

import pandas as pd

#importando
dados = pd.read_csv('aluguel.csv', sep = ';')
dados

type(dados)

dados.info()

dados.head(10)

"""## Informações gerais sobre a base de dados"""

dados.dtypes

tipos_de_dados = pd.DataFrame(dados.dtypes, columns = ['Tipos de dados'])

tipos_de_dados.columns.name = 'Variáveis'

tipos_de_dados

dados.shape

dados.shape[0]

dados.shape[1]

print('A base de dados apresenta {} registros (imóveis) e {} variáveis.'.format(dados.shape[0], dados.shape[1]))

