# -*- coding: utf-8 -*-
"""python-pandas-extras.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1L3rdwqTJ_qg6adyIIRtXbDpCNOAYu-Op

#Exercícios extras da aula sobre pandas
"""

import pandas as pd

json = open('aluguel.json')
print(json.read())

df_json = pd.read_json('aluguel.json')
df_json

txt = open('aluguel.txt')
print(txt.read())

df_txt = pd.read_table('aluguel.txt')
df_txt

df_xlsx = pd.read_excel('aluguel.xlsx')
df_xlsx

df_html = pd.read_html('dados_html_1.html')
df_html[0]

df_html = pd.read_html('dados_html_2.html')
df_html[0]

