# -*- coding: utf-8 -*-
"""tiposdeimoveis.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1D0Manof2G-26XNHZ1wKKIZAI3W_RZ6my

#Relatório de análise II

##Tipos de imóveis
"""

import pandas as pd

dados = pd.read_csv('aluguel.csv', sep = ';')

dados.head(10)

dados['Tipo']

tipo_de_imovel = dados['Tipo']

type(tipo_de_imovel)

tipo_de_imovel.drop_duplicates()

tipo_de_imovel.drop_duplicates(inplace = True)

tipo_de_imovel

"""O parâmetro inplace = True serve para alterar a tabela original com as modificações.

O método drop_duplicates() irá mostrar na célula o resultado mas não vai alterar a tabela original ainda.

##Organizando a visualização
"""

tipo_de_imovel = pd.DataFrame(tipo_de_imovel)

tipo_de_imovel

tipo_de_imovel.index

tipo_de_imovel.shape[0]

range(tipo_de_imovel.shape[0])

for i in range(tipo_de_imovel.shape[0]):
  print(i)

tipo_de_imovel.index = range(tipo_de_imovel.shape[0])

tipo_de_imovel

tipo_de_imovel.index

tipo_de_imovel

tipo_de_imovel.columns.name = 'Id'

tipo_de_imovel

